### ISSUE TITLE
Add DBAPI implementation

### ISSUE THREAD

**Issue by tonyyang-svail** [wangkuiyi/pysqlflow#3]
- [x] Add a DBAPI skeleton
- [ ] Add a grpc connection based on [sqlflow.proto](https://github.com/wangkuiyi/sqlflowserver/blob/develop/sqlflow.proto)
- [ ] Add [Type Objects and Constructors](https://www.python.org/dev/peps/pep-0249/#type-objects-and-constructors)
- [ ] Complete `execute` and `fetch`

**Comment by ktong** [comment]
Do we still need DBAPI if pysqlflow provides own magic command?

**Comment by tonyyang-svail** [comment]
> Do we still need DBAPI if pysqlflow provides own magic command?

Probably not.
